CREATE TABLE EMPLOYEE_HIST (
    EmpNo INTEGER NOT NULL,
    Sname VARCHAR(30) NOT NULL,
    JobLevel VARCHAR(30),
    JobStatus CHAR,
    DateHired DATE,
    Salary FLOAT,
    EmpAddress VARCHAR(30),
    CONSTRAINT emp_pk PRIMARY KEY (EmpNo)
);

INSERT INTO Employee VALUES
(11111, 'Cara Dulay', 'MGR', 'R', '2010-11-21', '10000', 'Manila');

DROP TRIGGER EMPLOYEE_DELETED;

CREATE 
    TRIGGER  EMPLOYEE_DELETED
 AFTER DELETE ON EMPLOYEE FOR EACH ROW 
    INSERT INTO EMPLOYEE_HIST VALUES (OLD.EmpNo , OLD.Sname , OLD.JobLevel , 
                                     OLD.JobStatus , OLD.DateHired , OLD.Salary, OLD.EmpAddress);

DELETE FROM EMPLOYEE
WHERE EmpNo = 11111;

DELETE FROM EMPLOYEE_HIST
WHERE EmpNo = 0;

SELECT * FROM EMPLOYEE_HIST;
SELECT * FROM EMPLOYEE;